name: Empty Commit

on:
  schedule:
    - cron: '30 23,7,15 * * *'  # Runs 11:30 PM, 7:30 AM, and 3:30 PM (15:30) UTC

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create empty commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Empty commit to keep repository active"
          git push 
